module.exports = [
    {
        id: 41,
        user_id: 1,
        cause_id: 14,
        amount: 283,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_fakecustomid',
        stripe_customer_id: 'cus_fakerandomid',
        Comments: [],
    },
    {
        id: 104,
        user_id: 1,
        cause_id: 14,
        amount: 16,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_1DtMgOCUXN1GgszpsVJx3eg8',
        stripe_customer_id: 'cus_EM4q5aP717vfHy',
        Comments: [],
    },
    {
        id: 105,
        user_id: 1,
        cause_id: 14,
        amount: 9,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_1DtMgOCUXN1GgszpsVJx3eg8',
        stripe_customer_id: 'cus_EM4q5aP717vfHy',
        Comments: [],
    },
    {
        id: 127,
        user_id: 1,
        cause_id: 14,
        amount: 17,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_1E4fuXCUXN1GgszpAJx3tCiP',
        stripe_customer_id: 'cus_EXlRJvXydgFbNj',
        Comments: [],
    },
    {
        id: 147,
        user_id: 1,
        cause_id: 14,
        amount: 1,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_1EOyD4CUXN1GgszpX0ZkcHhI',
        stripe_customer_id: 'cus_EsjgrDvzfIOsRj',
        Comments: [],
    },
    {
        id: 148,
        user_id: 1,
        cause_id: 14,
        amount: 14,
        email: 'test_user@testemail.com',
        stripe_id: 'ch_1EOyD4CUXN1GgszpX0ZkcHhI',
        stripe_customer_id: 'cus_EsjgrDvzfIOsRj',
        Comments: [],
    },
];
