/* eslint-disable no-unused-vars */
module.exports = {
    up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Causes', [
        {
            user_id: 1,
            org_id: null,
            name: 'I\'m visiting Canopy',
            type: 'Trip',
            goal_amount: 3500,
            description: "I will be on the ground in Kenya for 10 days this summer in which I'll be visiting the kids at Canopy Life Academy, seeing some of the kid's communities, and ending the trip with a Safari!",
            purpose: 'This will cover all administration fees (including VISA, park fees), airfare, lodging, and food while in Kenya.',
            icon: 'Africa',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/andrew-ruiz-348420.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/bill-wegener-285004.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Nairobi Sewing',
            type: 'Community Project',
            goal_amount: 10000,
            description: "We're adding a sewing facility outside of Nairobi, Kenya",
            purpose: 'We will be purchasing all of the building materials, as well as the production equipment to provide much needed jobs in this community.',
            icon: 'Globe',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/jens-johnsson-78101.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/madi-robson-113926.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Camp Anawana',
            type: 'Camp',
            goal_amount: 1500,
            description: 'Going to summer camp!',
            purpose: 'Your gift will help pay for room and board, admin fees, meals, and activities for the duration of the camp',
            icon: 'Airplane',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/khendi-lee-25583.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/jessica-castro-516921.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Technology classroom',
            type: '',
            goal_amount: 150000,
            description: 'Giving kids the tools to succeed',
            purpose: 'Building, computers, etc...',
            icon: 'Africa',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/Screen%20Shot%202018-06-21%20at%2010.16.52%20PM.png',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/seth-doyle-78210.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Oh baby!',
            type: 'Adoption',
            goal_amount: 35000,
            description: 'Adoption',
            purpose: 'Adopting',
            icon: 'Diaper',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/bastien-jaillot-175465.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/valeria-zoncoll-575958.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Feeding the homeless',
            type: 'Community Project',
            goal_amount: 300,
            description: 'Taking food to nearby homeless population',
            purpose: 'Completely for food',
            icon: 'Globe',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/jessica-lewis-512219-1.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/jessica-castro-516921-1.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Adopting this cute pup!',
            type: 'Adoption',
            goal_amount: 1200,
            description: 'This pup is just screaming for us to take him home...how can we resist?',
            purpose: 'All the paperwork, shots, meds, and supplies',
            icon: 'Diaper',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/hot_air_balloon.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/Fitz.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Video shoot',
            type: 'Community Project',
            goal_amount: 1500,
            description: 'This will help highlight some of the issues our community faces, in their own voices',
            purpose: 'Paying the videographer fees',
            icon: 'Globe',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/stephen-leonardi-417402-unsplash.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/laura-lee-moreau-9137-unsplash.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Drone Footage',
            type: 'Community Project',
            goal_amount: 1000,
            description: 'Drone Footage',
            purpose: 'Paying for the videographers services and fees',
            icon: 'Airplane',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/karl-greif-407484-unsplash.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/IMG_20150716_001102%20%282%29.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
        {
            user_id: 1,
            org_id: null,
            name: 'Film Stuff',
            type: 'Community Project',
            goal_amount: 750,
            description: 'Film Stuff',
            purpose: 'Film Stuff',
            icon: 'Airplane',
            featured: false,
            cover_image: 'https://generosity-market-cause-images.s3.amazonaws.com/coverImages/jon-flobrant-462801-unsplash.jpg',
            profile_image: 'https://generosity-market-cause-images.s3.amazonaws.com/profileImages/seth-doyle-78214-unsplash.jpg',
            createdAt: new Date(),
            updatedAt: new Date(),
            totalRaised: 0,
        },
    ], {}),

    down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Causes', null, {}),
};
